### ISSUE TITLE
Directive Pattern has problems when using templateUrl

### ISSUE THREAD

**Issue by hannahhoward** [michaelbromley/angular-es6#1]
Hi Michael,

   I noticed when I was playing with this that the directive class pattern has problems when you are using a templateUrl instead of a template on the directive. It seems angular's $compile copies the directive while it waits to fetch the template from the templateCache, and it fails to copy the prototype properties.

I believe you can fix this by changing the factory function to:

``` JavaScript
    factoryArray.push((...args) => {
      var directive = new ConstructorFn(...args);
      directive.link = directive.link;
      directive.compile = directive.compile;
      return directive;
    });
```

but then it wouldn't work as a generic factory function.

**Comment by michaelbromley** [comment]
Hi,

Thanks for the report & explanation. Still trying to fully get my head around what is going on here exactly - but your solution is good. I actually took a look at your implementation [in your a1atscript project](https://github.com/hannahhoward/a1atscript/blob/master/src/DirectiveObject.ats#L23) and saw that you figured out a way to generalize the solution.

So now I will borrow back from you. It's almost poetic :)
