### ISSUE TITLE
Possible typo with dependency injector/constructor?

### ISSUE THREAD

**Issue by SPGB** [michaelbromley/angular-es6#6]
Hi,

For instantiating I believe the second arg should be an array similar to `['dep1', 'dep2', ..., constructor() {}]` unless I am mistaken. However all of the examples follow this form:  `register('app').factory('thingFactory', ThingFactory);`

I believe the second arg should be `['$timeout', ThingFactory]`. Thanks.

**Comment by michaelbromley** [comment]
Hi,

The second argument can be an array _or_ a function. The array notation is a way to make the dependencies safe for minification - you can read more about it [here in the docs](https://docs.angularjs.org/guide/di#dependency-annotation). 

In the case of this project, I am using a build tool called "ngAnnotate" ([see gulpfile](https://github.com/michaelbromley/angular-es6/blob/master/gulpfile.js#L19)), which is designed to automatically provide these DI annotations without the developer having to worry about them.
